"""
musAI — Generative CAD Assistant
Flask backend with Gemini Function Calling + OpenSCAD code generation.
All OpenSCAD dimensions are in millimetres (mm).
"""

from flask import Flask, render_template, request
import google.generativeai as genai
import markdown
import re
import html as html_lib
from dotenv import load_dotenv
import os

load_dotenv()

app = Flask(__name__)


# ══════════════════════════════════════════════════════════════════════════════
# Jinja2 filter: lightweight OpenSCAD syntax highlighter
# ══════════════════════════════════════════════════════════════════════════════

SCAD_KEYWORDS = {
    "module", "function", "for", "if", "else", "true", "false",
    "include", "use", "let", "each",
}

def _highlight_scad(code: str) -> str:
    """
    Convert a plain SCAD string to HTML with CSS class spans.
    Order matters: comments first, then strings, then keywords/numbers.
    """
    lines = []
    for raw_line in code.split("\n"):
        line = html_lib.escape(raw_line)         # XSS-safe baseline

        # Comments  //...
        line = re.sub(
            r'(//.*?)$',
            r'<span class="sc-comment">\1</span>',
            line
        )

        # Only process non-comment portions for keywords/numbers
        def _process_token(m):
            tok = m.group(0)
            if tok in SCAD_KEYWORDS:
                return f'<span class="sc-keyword">{tok}</span>'
            return tok

        # Keywords (whole words only, skip inside comment spans)
        if 'sc-comment' not in line:
            line = re.sub(r'\b(' + '|'.join(SCAD_KEYWORDS) + r')\b', _process_token, line)

            # Numbers (int / float, not inside words)
            line = re.sub(
                r'(?<![a-zA-Z_])(\d+\.?\d*)',
                r'<span class="sc-number">\1</span>',
                line
            )

            # Module / function names (word immediately before '(')
            line = re.sub(
                r'\b([a-zA-Z_]\w*)\s*(?=\()',
                r'<span class="sc-module">\1</span>',
                line
            )

        lines.append(line)
    return "\n".join(lines)

app.jinja_env.filters["highlight_scad"] = _highlight_scad

# ── API key (use an env variable in production) ─────────────────────────────
genai.configure(api_key=os.getenv('GEMINI_API_KEY'))')


# ══════════════════════════════════════════════════════════════════════════════
# OpenSCAD Generator
# ══════════════════════════════════════════════════════════════════════════════

def _feature_header(features: list) -> str:
    if not features:
        return "// Features : (none)"
    return "// Features : " + ", ".join(features)


def _build_box(dim: dict, features: list) -> str:
    L = float(dim.get("length", 20))
    W = float(dim.get("width",  10))
    H = float(dim.get("height",  5))

    use_round   = "rounded_corners" in features
    use_hole    = "center_hole"     in features
    use_chamfer = "chamfer"         in features

    r      = round(min(L, W) / 10, 3)
    hole_d = round(min(L, W) / 4,  3)
    ch     = 1.0

    scad = f"""\
// ============================================================
// OpenSCAD Parametric Box  -  generated by musAI
// All units: mm
// ============================================================
{_feature_header(features)}

// Parameters
length    = {L};
width     = {W};
height    = {H};
fillet_r  = {r};
hole_d    = {hole_d};
chamfer   = {ch};
$fn       = 64;

module rounded_box(l, w, h, r) {{
    hull() {{
        for (x = [r, l - r])
        for (y = [r, w - r])
            translate([x, y, 0])
                cylinder(r = r, h = h);
    }}
}}

module chamfered_box(l, w, h, ch) {{
    hull() {{
        cube([l, w, h - ch]);
        translate([ch/2, ch/2, h - ch])
            cube([l - ch, w - ch, ch]);
    }}
}}

module box_part() {{
    difference() {{
"""
    if use_round:
        scad += "        rounded_box(length, width, height, fillet_r);\n"
    elif use_chamfer:
        scad += "        chamfered_box(length, width, height, chamfer);\n"
    else:
        scad += "        cube([length, width, height]);\n"

    if use_hole:
        scad += ("        translate([length/2, width/2, -0.1])\n"
                 "            cylinder(d = hole_d, h = height + 0.2);\n")

    scad += "    }\n}\n\nbox_part();\n"
    return scad


def _build_cylinder(dim: dict, features: list) -> str:
    D  = float(dim.get("diameter", 20))
    H  = float(dim.get("height",   10))

    use_hole    = "center_hole" in features
    use_chamfer = "chamfer"     in features

    hole_d = round(D / 4, 3)
    ch     = 1.0

    scad = f"""\
// ============================================================
// OpenSCAD Parametric Cylinder  -  generated by musAI
// All units: mm
// ============================================================
{_feature_header(features)}

// Parameters
diameter  = {D};
height    = {H};
hole_d    = {hole_d};
chamfer   = {ch};
$fn       = 128;

module chamfered_cylinder(d, h, ch) {{
    hull() {{
        cylinder(d = d,        h = h - ch);
        cylinder(d = d - 2*ch, h = h);
    }}
}}

module cylinder_part() {{
    difference() {{
"""
    if use_chamfer:
        scad += "        chamfered_cylinder(diameter, height, chamfer);\n"
    else:
        scad += "        cylinder(d = diameter, h = height);\n"

    if use_hole:
        scad += ("        translate([0, 0, -0.1])\n"
                 "            cylinder(d = hole_d, h = height + 0.2);\n")

    scad += "    }\n}\n\ncylinder_part();\n"
    return scad


def _build_bracket(dim: dict, features: list) -> str:
    L = float(dim.get("length",    40))
    W = float(dim.get("width",     20))
    H = float(dim.get("height",    40))
    T = float(dim.get("thickness",  4))

    use_hole  = "center_hole"     in features
    use_round = "rounded_corners" in features

    hole_d = round(min(W, H) / 4, 3)
    r      = round(T / 2, 3)

    scad = f"""\
// ============================================================
// OpenSCAD Parametric L-Bracket  -  generated by musAI
// All units: mm
// ============================================================
{_feature_header(features)}

// Parameters
length     = {L};
width      = {W};
height     = {H};
thickness  = {T};
fillet_r   = {r};
hole_d     = {hole_d};
$fn        = 64;

module bracket_part() {{
    difference() {{
        union() {{
            cube([length, width, thickness]);
            cube([thickness, width, height]);
        }}
"""
    if use_round:
        scad += ("        translate([thickness, -0.1, thickness])\n"
                 "            rotate([-90, 0, 0])\n"
                 "                cylinder(r = fillet_r, h = width + 0.2);\n")

    if use_hole:
        scad += ("        translate([length/2, width/2, -0.1])\n"
                 "            cylinder(d = hole_d, h = thickness + 0.2);\n"
                 "        translate([-0.1, width/2, height/2])\n"
                 "            rotate([0, 90, 0])\n"
                 "                cylinder(d = hole_d, h = thickness + 0.2);\n")

    scad += "    }\n}\n\nbracket_part();\n"
    return scad


def generate_openscad_code(part_type: str, dimensions: dict, features: list) -> dict:
    """
    Generate parametric OpenSCAD source code.
    Returns {"scad_code": str, "filename": str}.
    """
    supported = {"box", "cylinder", "bracket"}
    part_type = str(part_type).strip().lower()

    if part_type not in supported:
        raise ValueError(f"Unsupported part_type '{part_type}'. Use: {sorted(supported)}")

    for key, val in dimensions.items():
        if not isinstance(val, (int, float)):
            raise TypeError(f"Dimension '{key}' must be numeric, got {type(val).__name__}.")
        if float(val) <= 0:
            raise ValueError(f"Dimension '{key}' must be > 0 mm, got {val}.")

    features_lower = [str(f).strip().lower() for f in features]
    builders = {"box": _build_box, "cylinder": _build_cylinder, "bracket": _build_bracket}
    scad_code = builders[part_type](dimensions, features_lower)

    return {"scad_code": scad_code, "filename": f"{part_type}_part.scad"}


# ══════════════════════════════════════════════════════════════════════════════
# Gemini tool declaration
# ══════════════════════════════════════════════════════════════════════════════

OPENSCAD_TOOL = genai.protos.Tool(
    function_declarations=[
        genai.protos.FunctionDeclaration(
            name="generate_openscad_code",
            description=(
                "Generate a parametric OpenSCAD (.scad) script for a mechanical part. "
                "Call this whenever the user describes any part needing a 3-D CAD file."
            ),
            parameters=genai.protos.Schema(
                type=genai.protos.Type.OBJECT,
                properties={
                    "part_type": genai.protos.Schema(
                        type=genai.protos.Type.STRING,
                        description="'box', 'cylinder', or 'bracket'",
                    ),
                    "dimensions": genai.protos.Schema(
                        type=genai.protos.Type.OBJECT,
                        description=(
                            "Dimension key/value pairs in mm. "
                            "box: length, width, height. "
                            "cylinder: diameter, height. "
                            "bracket: length, width, height, thickness."
                        ),
                    ),
                    "features": genai.protos.Schema(
                        type=genai.protos.Type.ARRAY,
                        description=(
                            "Optional modifiers: "
                            "'rounded_corners', 'center_hole', 'chamfer'."
                        ),
                        items=genai.protos.Schema(type=genai.protos.Type.STRING),
                    ),
                },
                required=["part_type", "dimensions", "features"],
            ),
        )
    ]
)

SYSTEM_INSTRUCTION = (
    "You are musAI, an intelligent co-designer for mechanical parts. "
    "When the user describes a part concept, you MUST:\n"
    "  1. Call generate_openscad_code with best-fit parameters you infer from the description.\n"
    "  2. After the function result is returned, write a detailed engineering response covering:\n"
    "     a) Preliminary geometric parameters with units,\n"
    "     b) Design suggestions and trade-offs,\n"
    "     c) Material selection recommendations,\n"
    "     d) A beginner-friendly step-by-step CAD tutorial.\n"
    "Use markdown for structure. Be precise, educational, and encouraging."
)


# ══════════════════════════════════════════════════════════════════════════════
# Flask route
# ══════════════════════════════════════════════════════════════════════════════

@app.route("/", methods=["GET", "POST"])
def index():
    text_output = ""
    scad_code   = ""
    filename    = ""
    error       = ""

    if request.method == "POST":
        user_prompt = request.form.get("prompt", "").strip()
        if not user_prompt:
            error = "Please enter a design prompt."
        else:
            try:
                model = genai.GenerativeModel(
                    model_name="gemini-2.5-flash",
                    tools=[OPENSCAD_TOOL],
                    system_instruction=SYSTEM_INSTRUCTION,
                )
                chat = model.start_chat()

                # ── Turn 1: send user prompt ──────────────────────────────
                response = chat.send_message(user_prompt)

                # ── Detect and handle function call ───────────────────────
                fn_called = False
                for part in response.candidates[0].content.parts:
                    fc = getattr(part, "function_call", None)
                    if fc and fc.name == "generate_openscad_code":
                        fn_called = True

                        # Convert proto MapComposite → plain Python dict
                        args       = {k: v for k, v in fc.args.items()}
                        raw_dims   = args.get("dimensions", {})
                        dimensions = {k: float(v) for k, v in raw_dims.items()}
                        features   = list(args.get("features", []))
                        part_type  = str(args.get("part_type", "box"))

                        # Execute the OpenSCAD generator locally
                        fn_result = generate_openscad_code(part_type, dimensions, features)
                        scad_code = fn_result["scad_code"]
                        filename  = fn_result["filename"]

                        # ── Turn 2: return result to Gemini ───────────────
                        response2 = chat.send_message(
                            genai.protos.Content(
                                parts=[
                                    genai.protos.Part(
                                        function_response=genai.protos.FunctionResponse(
                                            name=fc.name,
                                            response={"result": fn_result},
                                        )
                                    )
                                ]
                            )
                        )
                        text_output = markdown.markdown(response2.text)
                        break   # one tool call per turn is expected

                if not fn_called:
                    # Gemini answered the prompt without calling the tool
                    text_output = markdown.markdown(response.text)

            except ValueError as ve:
                error = f"Validation error: {ve}"
            except Exception as e:
                error = f"An error occurred: {e}"

    return render_template(
        "index.html",
        text_output=text_output,
        scad_code=scad_code,
        filename=filename,
        error=error,
    )


if __name__ == "__main__":
    app.run(debug=True)
